import { FaultType, CandidateConfig, SubsystemHealth, TelemetryData } from '../types/satellite';

export interface ScenarioDefinition {
  type: FaultType;
  title: string;
  affectedSubsystem: keyof SubsystemHealth;
  description: string;
  anomalySignature: string;
  nominalConfig: string;
  recoveryConfig: string;
  baselinePerformance: number;   // %
  faultPerformance: number;      // %
  recoveredPerformance: number;  // %
  simpleFaultDetected: string;
  simpleFaultIsolated: string;
  simpleReconfigHeader: string;
  simpleReconfigActions: string[];
  simpleRecoveryVerified: string[];
  faultTelemetry: Partial<TelemetryData>;
  reconfiguredTelemetry: Partial<TelemetryData>;
  candidates: CandidateConfig[];
  aiDecisionLogs: {
    detect: string;
    isolate: string;
    evaluate: string;
    select: string;
    reconfigure: string;
    verify: string;
  };
}

export const FAULT_SCENARIOS: Record<Exclude<FaultType, 'none' | 'random'>, ScenarioDefinition> = {
  power: {
    type: 'power',
    title: 'Power Subsystem Fault',
    affectedSubsystem: 'power',
    description: 'Solar wing array partial degradation causes bus voltage sag and regulator trip.',
    anomalySignature: 'BUS_VOLT_DROP < 22.0V | EPS_OVERCURRENT | DRAIN_ALERT',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-07',
    baselinePerformance: 98,
    faultPerformance: 48,
    recoveredPerformance: 93,
    simpleFaultDetected: 'Power subsystem fault detected',
    simpleFaultIsolated: 'Affected subsystem: Power',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Reducing non-critical load',
      'Adjusting power allocation',
      'Protecting essential systems',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      busVoltage: 21.4,
      busCurrent: 19.8,
      batterySoc: 74.2,
      powerMargin: 11.5,
      solarGeneration: 410,
      cpuLoad: 68,
    },
    reconfiguredTelemetry: {
      busVoltage: 28.1,
      busCurrent: 14.9,
      batterySoc: 88.6,
      powerMargin: 46.2,
      solarGeneration: 780,
      cpuLoad: 31,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'Full Bus Bypass',
        status: 'rejected',
        rejectionReason: 'Exceeds power regulator limits; risk of secondary overload.',
        powerMargin: 14,
        thermalMargin: 42,
        commBandwidth: 100,
        attitudeStability: 96,
        resourceAvailability: 45,
        feasibilityScore: 32,
        actions: ['Bypass String #2 limiter', 'Force main bus tie'],
      },
      {
        id: 'C-02',
        name: 'Battery-Only Hold',
        status: 'rejected',
        rejectionReason: 'Battery drain too fast; reserves depleted in under 3 orbits.',
        powerMargin: 20,
        thermalMargin: 70,
        commBandwidth: 90,
        attitudeStability: 92,
        resourceAvailability: 30,
        feasibilityScore: 41,
        actions: ['Shed 40% non-essential payloads', 'Discharge secondary pack'],
      },
      {
        id: 'C-03',
        name: 'Direct MPPT Bridging',
        status: 'rejected',
        rejectionReason: 'Component heat exceeds safe operating temperature limit.',
        powerMargin: 38,
        thermalMargin: 28,
        commBandwidth: 85,
        attitudeStability: 89,
        resourceAvailability: 60,
        feasibilityScore: 54,
        actions: ['Bridge solar regulator to bus B', 'Reduce payload clock'],
      },
      {
        id: 'C-07',
        name: 'Isolated String Cross-Strapping',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 46,
        thermalMargin: 76,
        commBandwidth: 88,
        attitudeStability: 95,
        resourceAvailability: 92,
        feasibilityScore: 94,
        actions: [
          'Reducing non-critical load',
          'Adjusting power allocation',
          'Protecting essential systems',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Power subsystem fault detected: Bus voltage dropped to 21.4V.',
      isolate: 'Affected subsystem: Power.',
      evaluate: 'Searching for a safer operating configuration...',
      select: 'Recovery configuration selected: Isolated cross-strapped power mode.',
      reconfigure: 'Finding a safer operating configuration: Reducing non-critical load, adjusting power allocation, protecting essential systems.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  communication: {
    type: 'communication',
    title: 'Communication Subsystem Fault',
    affectedSubsystem: 'communication',
    description: 'Antenna gimbal mechanism stalls, causing signal attenuation and telemetry downlink loss.',
    anomalySignature: 'COMM_SNR_DROP < 0 dB | GIMBAL_STALL | CARRIER_LOCK_LOST',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-04',
    baselinePerformance: 98,
    faultPerformance: 39,
    recoveredPerformance: 92,
    simpleFaultDetected: 'Communication subsystem fault detected',
    simpleFaultIsolated: 'Affected subsystem: Communications',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Adjusting communication settings',
      'Optimizing data rate',
      'Checking link reliability',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      commMargin: -4.2,
      cpuLoad: 68,
      busVoltage: 27.8,
      powerMargin: 39.0,
    },
    reconfiguredTelemetry: {
      commMargin: 13.8,
      cpuLoad: 32,
      busVoltage: 28.2,
      powerMargin: 44.5,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'High-Torque Motor Overdrive',
        status: 'rejected',
        rejectionReason: 'Risk of permanent gear damage and attitude disturbance spike.',
        powerMargin: 30,
        thermalMargin: 65,
        commBandwidth: 40,
        attitudeStability: 42,
        resourceAvailability: 50,
        feasibilityScore: 35,
        actions: ['Double driver current to antenna gimbal motor'],
      },
      {
        id: 'C-02',
        name: 'Low-Rate Omni Beacon Only',
        status: 'rejected',
        rejectionReason: 'Bandwidth too low for primary mission data downlink.',
        powerMargin: 52,
        thermalMargin: 84,
        commBandwidth: 8,
        attitudeStability: 95,
        resourceAvailability: 90,
        feasibilityScore: 51,
        actions: ['Route all downlink via low-gain antennas'],
      },
      {
        id: 'C-04',
        name: 'Phased Array Synthesis & Nadir Slew',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 44,
        thermalMargin: 74,
        commBandwidth: 92,
        attitudeStability: 91,
        resourceAvailability: 88,
        feasibilityScore: 92,
        actions: [
          'Adjusting communication settings',
          'Optimizing data rate',
          'Checking link reliability',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Communication subsystem fault detected: Link margin dropped below 0 dB.',
      isolate: 'Affected subsystem: Communications.',
      evaluate: 'Searching for alternative communication settings and link paths...',
      select: 'Recovery configuration selected: Backup phased array link mode.',
      reconfigure: 'Finding a safer operating configuration: Adjusting communication settings, optimizing data rate, checking link reliability.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  thermal: {
    type: 'thermal',
    title: 'Thermal Subsystem Fault',
    affectedSubsystem: 'thermal',
    description: 'Radiator louver mechanism jams closed during high solar flux, causing avionics heat spike.',
    anomalySignature: 'CORE_TEMP > 80°C | RADIATOR_STAGNANT | THERMAL_DERATE',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-08',
    baselinePerformance: 98,
    faultPerformance: 52,
    recoveredPerformance: 94,
    simpleFaultDetected: 'Thermal subsystem fault detected',
    simpleFaultIsolated: 'Affected subsystem: Thermal',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Adjusting cooling',
      'Reducing thermal workload',
      'Checking temperature stability',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      coreTemp: 82.6,
      radiatorTemp: 64.2,
      cpuLoad: 78,
      powerMargin: 34.1,
      busVoltage: 27.6,
    },
    reconfiguredTelemetry: {
      coreTemp: 23.4,
      radiatorTemp: 12.1,
      cpuLoad: 35,
      powerMargin: 45.0,
      busVoltage: 28.2,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'Expendable Coolant Purge',
        status: 'rejected',
        rejectionReason: 'Non-reversible fluid release; shortens satellite lifespan.',
        powerMargin: 40,
        thermalMargin: 35,
        commBandwidth: 80,
        attitudeStability: 88,
        resourceAvailability: 20,
        feasibilityScore: 40,
        actions: ['Vent heat pipe secondary fluid'],
      },
      {
        id: 'C-03',
        name: 'Deep Eclipse Pitch Flip',
        status: 'rejected',
        rejectionReason: 'Cuts off solar power; triggers critical battery under-voltage.',
        powerMargin: 8,
        thermalMargin: 95,
        commBandwidth: 40,
        attitudeStability: 70,
        resourceAvailability: 55,
        feasibilityScore: 48,
        actions: ['Rotate solar arrays 180° into space shadow'],
      },
      {
        id: 'C-08',
        name: 'Passive Cold-Face Alignment & Radiator Shift',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 45,
        thermalMargin: 82,
        commBandwidth: 88,
        attitudeStability: 94,
        resourceAvailability: 91,
        feasibilityScore: 96,
        actions: [
          'Adjusting cooling',
          'Reducing thermal workload',
          'Checking temperature stability',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Thermal subsystem fault detected: Core bay temperature reached 82.6°C.',
      isolate: 'Affected subsystem: Thermal.',
      evaluate: 'Searching for balanced cooling and attitude profiles...',
      select: 'Recovery configuration selected: Deep-space cold-plate radiator alignment.',
      reconfigure: 'Finding a safer operating configuration: Adjusting cooling, reducing thermal workload, checking temperature stability.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  attitude: {
    type: 'attitude',
    title: 'Attitude Control Subsystem Fault',
    affectedSubsystem: 'attitude',
    description: 'Reaction wheel feedback anomaly causes pointing drift and nadir lock loss.',
    anomalySignature: 'ATTITUDE_DRIFT > 12.0° | RW_FEEDBACK_FAIL | TACH_ERROR',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-11',
    baselinePerformance: 98,
    faultPerformance: 32,
    recoveredPerformance: 95,
    simpleFaultDetected: 'Attitude control fault detected',
    simpleFaultIsolated: 'Affected subsystem: Attitude (ADCS)',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Adjusting control parameters',
      'Redistributing control effort',
      'Checking pointing stability',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      attitudeError: 14.8,
      adcsRpm: 5800,
      cpuLoad: 75,
      commMargin: 1.5,
      powerMargin: 33.0,
    },
    reconfiguredTelemetry: {
      attitudeError: 0.03,
      adcsRpm: 2850,
      cpuLoad: 30,
      commMargin: 14.2,
      powerMargin: 47.0,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'High-Rate Thruster Blasting',
        status: 'rejected',
        rejectionReason: 'Consumes excessive propellant; compromises future station-keeping.',
        powerMargin: 35,
        thermalMargin: 70,
        commBandwidth: 70,
        attitudeStability: 60,
        resourceAvailability: 32,
        feasibilityScore: 44,
        actions: ['Fire 4 RCS thruster pulses continuously'],
      },
      {
        id: 'C-04',
        name: 'Wheel Brake Hardlock',
        status: 'rejected',
        rejectionReason: 'Momentum transfer induces uncontrolled spacecraft spin.',
        powerMargin: 40,
        thermalMargin: 65,
        commBandwidth: 30,
        attitudeStability: 25,
        resourceAvailability: 60,
        feasibilityScore: 36,
        actions: ['Engage electromagnetic brake on wheel #2'],
      },
      {
        id: 'C-11',
        name: 'Skewed Wheel Redistribution & Magnetorquers',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 47,
        thermalMargin: 80,
        commBandwidth: 95,
        attitudeStability: 98,
        resourceAvailability: 94,
        feasibilityScore: 97,
        actions: [
          'Adjusting control parameters',
          'Redistributing control effort',
          'Checking pointing stability',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Attitude control fault detected: Pointing error reached 14.8° offset.',
      isolate: 'Affected subsystem: Attitude (ADCS).',
      evaluate: 'Searching for stable momentum redistribution configurations...',
      select: 'Recovery configuration selected: Redundant skewed wheel and magnetic damping.',
      reconfigure: 'Finding a safer operating configuration: Adjusting control parameters, redistributing control effort, checking pointing stability.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  sensor: {
    type: 'sensor',
    title: 'Sensor / Onboard Computer Fault',
    affectedSubsystem: 'sensors',
    description: 'Star tracker optical detector disturbance causes noisy attitude determination estimates.',
    anomalySignature: 'STAR_TRACKER_VALIDITY_0 | GYRO_DRIFT | ESTIMATE_UNCERTAIN',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-03',
    baselinePerformance: 98,
    faultPerformance: 56,
    recoveredPerformance: 93,
    simpleFaultDetected: 'Sensor anomaly detected',
    simpleFaultIsolated: 'Affected subsystem: Sensors',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Reducing non-critical processing',
      'Redistributing computing load',
      'Checking system stability',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      attitudeError: 6.2,
      cpuLoad: 72,
      commMargin: 8.5,
      busVoltage: 27.9,
    },
    reconfiguredTelemetry: {
      attitudeError: 0.04,
      cpuLoad: 28,
      commMargin: 14.0,
      busVoltage: 28.3,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'Detector Gain Overdrive',
        status: 'rejected',
        rejectionReason: 'Sensor saturation persists under current lighting conditions.',
        powerMargin: 42,
        thermalMargin: 70,
        commBandwidth: 75,
        attitudeStability: 50,
        resourceAvailability: 60,
        feasibilityScore: 48,
        actions: ['Lower exposure and adjust threshold of Star Tracker #1'],
      },
      {
        id: 'C-03',
        name: 'Redundant Star Tracker & Sun Sensor Fusion',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 46,
        thermalMargin: 78,
        commBandwidth: 94,
        attitudeStability: 96,
        resourceAvailability: 92,
        feasibilityScore: 95,
        actions: [
          'Reducing non-critical processing',
          'Redistributing computing load',
          'Checking system stability',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Sensor anomaly detected: Primary star tracker attitude estimate variance high.',
      isolate: 'Affected subsystem: Sensors.',
      evaluate: 'Searching for alternative sensor fusion configurations...',
      select: 'Recovery configuration selected: Secondary tracker and sun sensor fusion.',
      reconfigure: 'Finding a safer operating configuration: Reducing non-critical processing, redistributing computing load, checking system stability.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  stress: {
    type: 'stress',
    title: 'Severe Stress Case (Experiment B Event #07)',
    affectedSubsystem: 'power',
    description: 'High-severity compound stress event impacting power and thermal subsystems simultaneously.',
    anomalySignature: 'COMPOUND_STRESS_EVENT | EPS_VOLT_DROP | THERMAL_SURGE',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-09',
    baselinePerformance: 98,
    faultPerformance: 34,
    recoveredPerformance: 89,
    simpleFaultDetected: 'Severe multi-subsystem stress fault detected',
    simpleFaultIsolated: 'Affected subsystems: Power & Thermal (Compound Stress)',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Shedding non-critical loads',
      'Adjusting power allocation',
      'Activating secondary cooling',
      'Protecting essential systems',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      busVoltage: 21.2,
      busCurrent: 21.8,
      batterySoc: 71.0,
      coreTemp: 76.5,
      powerMargin: 14.5,
      cpuLoad: 76,
      solarGeneration: 420,
    },
    reconfiguredTelemetry: {
      busVoltage: 27.9,
      busCurrent: 15.1,
      batterySoc: 86.8,
      coreTemp: 24.2,
      powerMargin: 41.5,
      cpuLoad: 33,
      solarGeneration: 760,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'Direct Full Bus Tie',
        status: 'rejected',
        rejectionReason: 'Exceeds PDU circuit breaker rating; secondary overcurrent risk.',
        powerMargin: 12,
        thermalMargin: 20,
        commBandwidth: 90,
        attitudeStability: 90,
        resourceAvailability: 40,
        feasibilityScore: 28,
        actions: ['Force main bus tie closure'],
      },
      {
        id: 'C-02',
        name: 'Deep Eclipse Pitch Flip',
        status: 'rejected',
        rejectionReason: 'Battery depth of discharge exceeds 65% in 3 orbits; mission loss risk.',
        powerMargin: 15,
        thermalMargin: 80,
        commBandwidth: 50,
        attitudeStability: 75,
        resourceAvailability: 35,
        feasibilityScore: 38,
        actions: ['Pitch arrays into shadow'],
      },
      {
        id: 'C-03',
        name: 'Primary Louver Overdrive',
        status: 'rejected',
        rejectionReason: 'Core temperature in avionics bay B exceeds +85°C safety limit.',
        powerMargin: 30,
        thermalMargin: 25,
        commBandwidth: 70,
        attitudeStability: 85,
        resourceAvailability: 50,
        feasibilityScore: 46,
        actions: ['Force louver motor maximum torque'],
      },
      {
        id: 'C-08',
        name: 'Compound Load Shedding & Cross-Strapped Thermal Shunt',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 42,
        thermalMargin: 74,
        commBandwidth: 82,
        attitudeStability: 92,
        resourceAvailability: 88,
        feasibilityScore: 91,
        actions: [
          'Shedding non-critical loads',
          'Adjusting power allocation',
          'Activating secondary cooling',
          'Protecting essential systems',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Severe multi-subsystem stress fault detected across power and thermal channels.',
      isolate: 'Affected subsystems: Power & Thermal (Compound Stress).',
      evaluate: 'Searching for a survivable recovery configuration across candidate topologies...',
      select: 'Recovery configuration selected: Compound load shedding and cross-strapped distribution.',
      reconfigure: 'Finding a safer operating configuration: Shedding non-critical loads, adjusting power allocation, activating secondary cooling.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },

  unrecoverable_stress: {
    type: 'unrecoverable_stress',
    title: 'Severe Stress Case (Experiment B Event #07)',
    affectedSubsystem: 'power',
    description: 'High-severity compound stress event from Experiment B population demonstrating autonomous recovery.',
    anomalySignature: 'COMPOUND_STRESS_EVENT | EPS_VOLT_DROP | THERMAL_SURGE',
    nominalConfig: 'NOMINAL-01',
    recoveryConfig: 'RECOVERY-09',
    baselinePerformance: 98,
    faultPerformance: 34,
    recoveredPerformance: 89,
    simpleFaultDetected: 'Severe multi-subsystem stress fault detected',
    simpleFaultIsolated: 'Affected subsystems: Power & Thermal (Compound Stress)',
    simpleReconfigHeader: 'Finding a safer operating configuration...',
    simpleReconfigActions: [
      'Shedding non-critical loads',
      'Adjusting power allocation',
      'Activating secondary cooling',
      'Protecting essential systems',
    ],
    simpleRecoveryVerified: [
      'Safe configuration found',
      'Mission performance restored',
      'System continues operating',
    ],
    faultTelemetry: {
      busVoltage: 21.2,
      busCurrent: 21.8,
      batterySoc: 71.0,
      coreTemp: 76.5,
      powerMargin: 14.5,
      cpuLoad: 76,
      solarGeneration: 420,
    },
    reconfiguredTelemetry: {
      busVoltage: 27.9,
      busCurrent: 15.1,
      batterySoc: 86.8,
      coreTemp: 24.2,
      powerMargin: 41.5,
      cpuLoad: 33,
      solarGeneration: 760,
    },
    candidates: [
      {
        id: 'C-01',
        name: 'Direct Full Bus Tie',
        status: 'rejected',
        rejectionReason: 'Exceeds PDU circuit breaker rating; secondary overcurrent risk.',
        powerMargin: 12,
        thermalMargin: 20,
        commBandwidth: 90,
        attitudeStability: 90,
        resourceAvailability: 40,
        feasibilityScore: 28,
        actions: ['Force main bus tie closure'],
      },
      {
        id: 'C-08',
        name: 'Compound Load Shedding & Cross-Strapped Thermal Shunt',
        status: 'safe',
        rejectionReason: undefined,
        powerMargin: 42,
        thermalMargin: 74,
        commBandwidth: 82,
        attitudeStability: 92,
        resourceAvailability: 88,
        feasibilityScore: 91,
        actions: [
          'Shedding non-critical loads',
          'Adjusting power allocation',
          'Activating secondary cooling',
          'Protecting essential systems',
        ],
      },
    ],
    aiDecisionLogs: {
      detect: 'Severe multi-subsystem stress fault detected across power and thermal channels.',
      isolate: 'Affected subsystems: Power & Thermal (Compound Stress).',
      evaluate: 'Searching for a survivable recovery configuration across candidate topologies...',
      select: 'Recovery configuration selected: Compound load shedding and cross-strapped distribution.',
      reconfigure: 'Finding a safer operating configuration: Shedding non-critical loads, adjusting power allocation, activating secondary cooling.',
      verify: 'Recovery verified: Safe configuration found, mission performance restored, system continues operating.',
    },
  },
};
